### ISSUE TITLE
SIGINT is not properly handled when using ZNC

### ISSUE THREAD

**Issue by JanGe** [JanGe/xdcc#9]
@cbm80 writes in #4:

> The problem that xdcc doesn't send proper xdcc cancel messages seems to persist, as does the handling of ctrl-c in combination with ZNC.

and in #8:

> The only things that do not appear to have changed from the old version are the handling of ctrl-c and sending disconnect to ZNC prior to closing the connection.

I'll have to actually install ZNC to debug this. Could take a few days until I get around to look into this though.

**Comment by JanGe** [comment]
Ah, I didn't realise so far, that `irc-client` does not call `_ondisconnect` when receiving `SIGINT`. Makes sense now...

**Comment by JanGe** [comment]
This should be fixed in [commit 6b3cad](https://github.com/JanGe/xdcc/commit/6b3cad390c527328135de668d7b1d0b44cd1748b). I basically install a signal handler when `XDCC SEND` is sent that calsl `XDCC CANCEL` and disconnects from the network which then triggers the `onDisconnect` function with the ZNC hook.

@cbm80 Is there still a case missing that I didn't think of?

**Comment by cbm80** [comment]
Basically, IF initially ZNC greeted xdcc with its welcome message and xdcc responded by sending `connect`, THEN you have to make sure that a `disconnect` message is issued to ZNC prior to closing the connection (and after `xdcc cancel`) is send.

IF initially ZNC did not greet xdcc with a welcome message, no `connect` message must be send and thus a `disconnect` is message unnecessary prior to closing the connection.

Other than that xdcc works charmingly well now.

**Comment by JanGe** [comment]
Alright, [commit df1db8](https://github.com/JanGe/xdcc/commit/df1db807f47ce40ccce9c1ded43c6bd4a6f7628f) should fix this then. :)

**Comment by cbm80** [comment]
A bit of debugging revealed that `disconnect` is still not send properly. I have no time to really dig into this, perhaps you should install ZNC and try it out yourself.
